# Clock
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

# set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
# set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
# set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
# set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
# set_property PACKAGE_PIN V2 [get_ports {sw[8]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
# set_property PACKAGE_PIN T3 [get_ports {sw[9]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
# set_property PACKAGE_PIN T2 [get_ports {sw[10]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
# set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
# set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
# set_property PACKAGE_PIN U1 [get_ports {sw[13]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
# set_property PACKAGE_PIN T1 [get_ports {sw[14]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
# set_property PACKAGE_PIN R2 [get_ports {sw[15]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]

set_property PACKAGE_PIN V17 [get_ports SW0]
set_property PACKAGE_PIN V16 [get_ports SW1]
set_property PACKAGE_PIN W16 [get_ports SW2]
set_property PACKAGE_PIN W17 [get_ports SW3]
#set_property PACKAGE_PIN U17 [get_ports _volDOWN]
#set_property PACKAGE_PIN T18 [get_ports _volUP]
#set_property IOSTANDARD LVCMOS33 [get_ports _volUP]
#set_property IOSTANDARD LVCMOS33 [get_ports _volDOWN]
set_property IOSTANDARD LVCMOS33 [get_ports SW3]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property IOSTANDARD LVCMOS33 [get_ports SW0]
set_property IOSTANDARD LVCMOS33 [get_ports SW2]
#set_property IOSTANDARD LVCMOS33 [get_ports {_vol[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {_vol[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {_vol[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {_vol[0]}]
#set_property PACKAGE_PIN U16 [get_ports {_vol[0]}]
#set_property PACKAGE_PIN E19 [get_ports {_vol[1]}]
#set_property PACKAGE_PIN U19 [get_ports {_vol[2]}]
#set_property PACKAGE_PIN V19 [get_ports {_vol[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {DIGIT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIGIT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIGIT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIGIT[0]}]
set_property PACKAGE_PIN W4 [get_ports {DIGIT[3]}]
set_property PACKAGE_PIN V4 [get_ports {DIGIT[2]}]
set_property PACKAGE_PIN U4 [get_ports {DIGIT[1]}]
set_property PACKAGE_PIN U2 [get_ports {DIGIT[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[0]}]
set_property PACKAGE_PIN W7 [get_ports {DISPLAY[6]}]
set_property PACKAGE_PIN W6 [get_ports {DISPLAY[5]}]
set_property PACKAGE_PIN U8 [get_ports {DISPLAY[4]}]
set_property PACKAGE_PIN V8 [get_ports {DISPLAY[3]}]
set_property PACKAGE_PIN U5 [get_ports {DISPLAY[2]}]
set_property PACKAGE_PIN V5 [get_ports {DISPLAY[1]}]
set_property PACKAGE_PIN U7 [get_ports {DISPLAY[0]}]

set_property PACKAGE_PIN U16 [get_ports {_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {_led[0]}]
set_property PACKAGE_PIN E19 [get_ports {_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {_led[1]}]
set_property PACKAGE_PIN U19 [get_ports {_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {_led[2]}]
set_property PACKAGE_PIN V19 [get_ports {_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {_led[3]}]
#set_property PACKAGE_PIN W18 [get_ports {_led[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {_led[4]}]
#set_property PACKAGE_PIN U15 [get_ports {_led[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {_led[5]}]
#set_property PACKAGE_PIN U14 [get_ports {_led[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {_led[6]}]
#set_property PACKAGE_PIN V14 [get_ports {_led[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {_led[7]}]

# Pmod JA
set_property PACKAGE_PIN G2 [get_ports RxD]
	set_property IOSTANDARD LVCMOS33 [get_ports RxD]
set_property PACKAGE_PIN H1 [get_ports audio_mclk]
	set_property IOSTANDARD LVCMOS33 [get_ports audio_mclk]
set_property PACKAGE_PIN K2 [get_ports audio_lrck]
	set_property IOSTANDARD LVCMOS33 [get_ports audio_lrck]
set_property PACKAGE_PIN H2 [get_ports audio_sck]
	set_property IOSTANDARD LVCMOS33 [get_ports audio_sck]
set_property PACKAGE_PIN G3 [get_ports audio_sdin]
	set_property IOSTANDARD LVCMOS33 [get_ports audio_sdin]

# Pmod JB
set_property PACKAGE_PIN A14 [get_ports IN1]
	set_property IOSTANDARD LVCMOS33 [get_ports IN1]
set_property PACKAGE_PIN A16 [get_ports IN2]
	set_property IOSTANDARD LVCMOS33 [get_ports IN2]
set_property PACKAGE_PIN B15 [get_ports IN3]
	set_property IOSTANDARD LVCMOS33 [get_ports IN3]
set_property PACKAGE_PIN B16 [get_ports IN4]
	set_property IOSTANDARD LVCMOS33 [get_ports IN4]

# Pmod JC
set_property PACKAGE_PIN K17 [get_ports left_led]
	set_property IOSTANDARD LVCMOS33 [get_ports left_led]
set_property PACKAGE_PIN M18 [get_ports right_led]
	set_property IOSTANDARD LVCMOS33 [get_ports right_led]
set_property PACKAGE_PIN N17 [get_ports Trig]
	set_property IOSTANDARD LVCMOS33 [get_ports Trig]
set_property PACKAGE_PIN P18 [get_ports Echo]
	set_property IOSTANDARD LVCMOS33 [get_ports Echo]

set_property CFGBVS Vcco [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
